### PR TITLE
Sign in Use Case

### PR DESCRIPTION
**Pull request by umairx25**
Added sign in functionality using firebase, with full clean architecture. Added methods to change and retrieve user data from users for future use in other use cases. Cleaned up the build class .

### CODE REVIEW

**Comment by SameerShahed71** [comment]
This pull request implements functionality for user sign-up and the modular construction of application views, adhering well to Clean Architecture principles. The code is organized, with clear separation of concerns between interactors, controllers, and views. However, some naming inconsistencies exist; for example, variables such as SignupPresenter and SignupInputData in SignupInteractor do not follow Javas camelCase convention and should be renamed to signupPresenter and signupInputData for consistency. Additionally, commented-out code in SignupInteractor.execute related to email validation should be either removed or updated with a proper implementation to enhance clarity.

Error handling in Firebase initialization is insufficient. The initialize_firebase method in Builder assumes the availability of the credentials file without verification. Adding checks to ensure the file exists and handling potential exceptions would make the application more robust. Furthermore, the addChartView method reinitializes ChartViewModel, which may lead to inconsistencies with the shared state. Reusing existing instances or clarifying their purpose would improve reliability and maintainability.

Documentation and testing need significant improvement. Critical methods like execute in SignupInteractor and addHomeView in Builder lack Javadoc, making it harder for team members to understand their purpose. Adding unit tests for SignupInteractor to validate scenarios such as successful sign-up, duplicate users, and invalid credentials would strengthen test coverage. Similarly, UI components like the cardPanel and view transitions in Builder should have integration tests to ensure smooth navigation and state handling. Overall, this is a well-structured contribution, and addressing these issues will enhance the quality and maintainability of the project.

**Comment by aneeqmuh** [comment]
This implementation demonstrates a solid understanding of Firebase integration and Clean Architecture principles, with clear separation of concerns between the SignupInteractor, Builder, and UserDataAccess classes. However, there are areas for improvement, including adding unit tests for critical methods like signup and existingUser, enhancing error handling with detailed logging, and improving documentation by adding Javadoc for public methods. Refactoring duplicated logic in database methods, replacing hardcoded dependencies with dynamic configurations, and using a logging framework instead of System.out.println would also improve maintainability. Addressing these areas will make the code more robust, readable, and easier to debug, Good Work Umair.

**Review by aneeqmuh — COMMENTED** [review]
This implementation demonstrates a solid understanding of Firebase integration and Clean Architecture principles, with clear separation of concerns between the SignupInteractor, Builder, and UserDataAccess classes. However, there are areas for improvement, including adding unit tests for critical methods like signup and existingUser, enhancing error handling with detailed logging, and improving documentation by adding Javadoc for public methods. Refactoring duplicated logic in database methods, replacing hardcoded dependencies with dynamic configurations, and using a logging framework instead of System.out.println would also improve maintainability. Addressing these areas will make the code more robust, readable, and easier to debug, Good Work Umair.

**Review by SameerShahed71 — APPROVED** [review]
This pull request implements functionality for user sign-up and the modular construction of application views, adhering well to Clean Architecture principles. The code is organized, with clear separation of concerns between interactors, controllers, and views. However, some naming inconsistencies exist; for example, variables such as SignupPresenter and SignupInputData in SignupInteractor do not follow Javas camelCase convention and should be renamed to signupPresenter and signupInputData for consistency. Additionally, commented-out code in SignupInteractor.execute related to email validation should be either removed or updated with a proper implementation to enhance clarity.

Error handling in Firebase initialization is insufficient. The initialize_firebase method in Builder assumes the availability of the credentials file without verification. Adding checks to ensure the file exists and handling potential exceptions would make the application more robust. Furthermore, the addChartView method reinitializes ChartViewModel, which may lead to inconsistencies with the shared state. Reusing existing instances or clarifying their purpose would improve reliability and maintainability.

Documentation and testing need significant improvement. Critical methods like execute in SignupInteractor and addHomeView in Builder lack Javadoc, making it harder for team members to understand their purpose. Adding unit tests for SignupInteractor to validate scenarios such as successful sign-up, duplicate users, and invalid credentials would strengthen test coverage. Similarly, UI components like the cardPanel and view transitions in Builder should have integration tests to ensure smooth navigation and state handling. Overall, this is a well-structured contribution, and addressing these issues will enhance the quality and maintainability of the project.

**Pull request merged**
